server {
    listen 80;
    server_name localhost;

    location /app {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /app/index.html;
    }

    location /quiz {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /quiz/index.html;
    }

    location /api/ {
        proxy_pass http://api-gateway:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
} 