server.port=8081
spring.application.name=user-service

# Konfiguracja bazy danych
spring.datasource.url=jdbc:postgresql://postgres:5432/elearning
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Konfiguracja JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=users

# Konfiguracja JWT
# jwt.secret=elearningSecretKeyVeryLongAndSecureKeyForJWTTokenGeneration # Stary klucz
# jwt.expiration=86400000 # Stary klucz
elearning.app.jwtSecret=elearningSecretKeyVeryLongAndSecureKeyForJWTTokenGeneration
elearning.app.jwtExpirationMs=86400000 