server.port=8082
spring.application.name=flashcard-service

# Konfiguracja bazy danych
spring.datasource.url=jdbc:postgresql://postgres:5432/elearning
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Konfiguracja JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=flashcards

# Konfiguracja dla User Service
user-service.url=http://user-service:8081 